from game.utils.floor_transition import floor_transition
from ..graphics.sprite import Sprite
from ..core import GameMaster, Interactable
from . import TileEntity

class Stairs(TileEntity, Interactable):
  def __init__(self, generator):
    super().__init__()
    self.require(Sprite)
    self.generator = generator

  def start(self):
    self.get_component(Sprite).set_sprite("assets/tiles/stairs.png")

  def interact(self, entity):
    #transition the game to the new world generated by our generator
    self.entity.world.find_component(GameMaster).game.transition(lambda world: floor_transition(world, self.generator))
