from components.tiles import TileEntity
from components.graphics.sprite import Sprite
from components.core.game_master import GameMaster
from components.core.interactable import Interactable
from utils.floor_transition import floor_transition

class Stairs(TileEntity, Interactable):
  def __init__(self, generator):
    super().__init__()
    self.require(Sprite)
    self.generator = generator

  def start(self):
    self.get_component(Sprite).set_sprite("assets/tiles/stairs.png")

  def interact(self, entity):
    #transition the game to the new world generated by our generator
    self.entity.world.find(GameMaster)[0].get_component(GameMaster).game.transition(floor_transition(self.generator))
